# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "PQuj5u9r9J22UAgjeu0unfZewE48Y1PFmzD+o3QHpc/lPqFoDKvUY+pjAOsCXuV4DBORLGLKs+oZBFmb1yliBZBm6nO1Yj2JutlwyFRKUBTJkEi5Xn12adAYRI0THaQ5/b0kKPonxOuA/4ksoC2myqX7izz+Z6qKgSwJanKHrvA="

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/uftpd"
      description: "uftpd -- the no nonsense (T)FTP server"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen && ./configure"
    build_command: "make -j5 clean all"
    branch_pattern: dev

script:
  - ./autogen.sh
  - ./configure --disable-silent-rules --prefix=
  - make clean
  - make -j5
  - DESTDIR=~/tmp make install
  - tree ~/tmp
  - ldd ~/tmp/sbin/uftpd
